import {Component, OnInit} from '@angular/core';
import {Router} from "@angular/router";
import {CommonModule} from "@angular/common";
import {BackgroundSkyComponent} from "../background-sky-scene/background-sky.component";


@Component({
  selector: 'app-scene-overview',
  standalone: true,
  imports: [CommonModule, BackgroundSkyComponent],
  templateUrl: './scene-overview.component.html',
  styleUrls: ['./scene-overview.component.css']
})
export class SceneOverviewComponent implements OnInit {
  private mouseX: number = 0;
  private mouseY: number = 0;

  public examples = [
    {name: '1. About', route: '/about', description: '1. Information about the application and its purpose.'},
    {name: '2. Links', route: '/links', description: '2. Useful links related to the application.'},
    {name: '3. Gallery', route: '/sprites', description: '3. Assets Generated By ChatGpt for this project'},
    {
      name: '4. Info',
      route: '/chatgpt-4',
      description: '4. Information about features of  ChatGPT 4o, Angular and Three.js .'
    },
    {
      name: '1. Cube',
      route: '/scenes/cube-example',
      description: '1. This example demonstrates a simple 3D rotating cube using Three.js.'
    },
    {
      name: '2. Tetris',
      route: '/scenes/tetris-scene',
      description: '2. This example showcases a Tetris game implemented with Angular and Three.js.'
    },
    {
      name: '3. 2D Plane Movement',
      route: '/scenes/office',
      description: '3. 2D scene  where the camera is fixed and movement bound to a 2D Plane'
    },
    {
      name: '4. 3D Space Movement ',
      route: '/scenes/bubble-scene',
      description: '4. 3D model movement in 3D space  { Press W,A,S,D  ->  E , Shift} to control 3D object it 3D space.'
    },
    {name: '5. 3D Game ', route: '/scenes/test-3d', description: '5. 3D model animated example.'},
  ];

  constructor(private router: Router) {
  }

  ngOnInit(): void {
  }

  navigateTo(route: string): void {
    this.router.navigate([route]);
  }
}
