import {Component, HostListener, OnInit} from '@angular/core';
import { Router } from "@angular/router";
import { CommonModule } from "@angular/common";
import {
  AmbientLight,
  DirectionalLight,
  EquirectangularReflectionMapping,
  LoadingManager,
  PerspectiveCamera,
  Scene,
  WebGLRenderer
} from "three";
import { RGBELoader } from "three/examples/jsm/loaders/RGBELoader.js";
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';


@Component({
  selector: 'app-scene-overview',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './scene-overview.component.html',
  styleUrls: ['./scene-overview.component.css']
})
export class SceneOverviewComponent implements OnInit {
  private loadingManager!: LoadingManager;
  private camera!: PerspectiveCamera;
  private renderer!: WebGLRenderer;
  private orbitControls!: OrbitControls;
  private mouseX: number = 0;
  private mouseY: number = 0;

  private scene!: Scene;

  public examples = [
    { name: '1. About', route: '/about', description: 'Information about the application and its purpose.' },
    { name: '2. Links', route: '/links', description: 'Useful links related to the application.' },
    { name: '3. Generated Sprite Sets', route: '/sprites', description: 'Assets Generated By ChatGpt for this project' },
    { name: '4. ChatGPT 4o', route: '/chatgpt-4', description: 'Information about the ChatGPT 4o model and its features.' },
    { name: '1. Cube Example', route: '/scenes/cube-example', description: 'This example demonstrates a simple 3D rotating cube using Three.js.' },
    { name: '2. Tetris Scene', route: '/scenes/tetris-scene', description: 'This example showcases a Tetris game implemented with Angular and Three.js.' },
    { name: '3. Office Scene', route: '/scenes/office', description: 'Office scene built from image uploaded, recorded with camera.' },
    { name: '4. Bubble', route: '/scenes/bubble-scene', description: 'Bubble scene example.' },
    { name: '5. 3D Model Animated', route: '/scenes/test-3d', description: '3D model animated example.' },
  ];

  constructor(private router: Router) {}

  ngOnInit(): void {
    this.initScene();
    this.animate();
  }

  @HostListener('document:mousemove', ['$event'])
  onMouseMove(event: MouseEvent) {
    console.log('MOuse X');
    this.mouseX = (event.clientX / window.innerWidth) * 2 - 1;
    this.mouseY = -(event.clientY / window.innerHeight) * 2 + 1;
  }

  navigateTo(route: string): void {
    this.router.navigate([route]);
  }

  initScene() {
    this.loadingManager = new LoadingManager();
    // Basic setup
    this.scene = new Scene();
    this.camera = new PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
    this.renderer = new WebGLRenderer({ antialias: true });
    this.renderer.setPixelRatio(window.devicePixelRatio);
    this.renderer.setSize(window.innerWidth, window.innerHeight);
    const container = document.getElementById('container');
    if (container) {
      container.appendChild(this.renderer.domElement);
    } else {
      console.error('Container element not found');
      return;
    }

    // Skybox setup
    this.addSkyTexture();

    // Camera position
    this.camera.position.z = 5;
    this.addLights();

    // CONTROLS
    this.orbitControls = new OrbitControls(this.camera, this.renderer.domElement);
    this.orbitControls['enableDamping'] = true;
    this.orbitControls['minDistance'] = 20;
    this.orbitControls['maxDistance'] = 70;
    this.orbitControls['enablePan'] = false;
    this.orbitControls['maxPolarAngle'] = Math.PI / 2 - 0.05;
    this.orbitControls.update();
  }

  private addLights(): void {
    this.scene.add(new AmbientLight(0xffffff, 0.7));
    const dirLight = new DirectionalLight(0xffffff, 1);
    dirLight.position.set(-60, 100, -10);
    dirLight.castShadow = true;
    dirLight.shadow.camera.top = 50;
    dirLight.shadow.camera.bottom = -50;
    dirLight.shadow.camera.left = -50;
    dirLight.shadow.camera.right = 50;
    dirLight.shadow.camera.near = 0.1;
    dirLight.shadow.camera.far = 200;
    dirLight.shadow.mapSize.width = 4096;
    dirLight.shadow.mapSize.height = 4096;
    this.scene.add(dirLight);
  }

  private addSkyTexture(): void {
    const rgbeLoader = new RGBELoader(this.loadingManager);
    rgbeLoader.load('assets/textures/sky/sky.hdr', (texture) => {
      texture.mapping = EquirectangularReflectionMapping;
      this.scene.background = texture;
      this.scene.environment = texture; // Optional: to use the texture for environment lighting
      console.log('Sky texture loaded successfully');
    }, undefined, (error) => {
      console.error('Error loading sky texture', error);
    });
  }

  // Render the scene

  animate() {
    requestAnimationFrame(() => this.animate());
    this.camera.position.x += (this.mouseX * 10 - this.camera.position.x) * 0.05;
    this.camera.position.y += (this.mouseY * 10 - this.camera.position.y) * 0.05;
    this.camera.lookAt(this.scene.position);
    this.orbitControls.update();
    this.renderer.render(this.scene, this.camera);
  }
}
